// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SentimentAnalysis.API.Models
{
   public partial class TrainModel
   {
      public int Id { get; set; }
      public string Message { get; set; }
      public int Result { get; set; }
   }
}
