// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SentimentAnalysis.API.Data;
using SentimentAnalysis.API.Models;

#nullable disable

namespace SentimentAnalysis.API.Data
{
	public partial class TrainModelContext : DbContext
	{
		public TrainModelContext()
		{
		}

		public TrainModelContext(DbContextOptions<TrainModelContext> options)
			: base(options)
		{
		}

		public virtual DbSet<TrainModel> TrainData { get; set; }
		public virtual DbSet<StoredMessage> StoredMessages { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlite(@"Filename=trainBotData.db");
			base.OnConfiguring(optionsBuilder);
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

			OnModelCreatingPartial(modelBuilder);
		}

		partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
	}
}
